artifacts_root : artifacts

data_ingestion : 
  root_dir : artifacts/data_ingestion
  source_url : https://raw.githubusercontent.com/kartheek2003/data_zip_repo/main/online_retail.xlsx
  local_data_file : artifacts/data_ingestion/online_retail.xlsx

  