artifacts_root : artifacts

data_ingestion : 
  root_dir : artifacts/data_ingestion
  source_url : https://raw.githubusercontent.com/kartheek2003/data_zip_repo/main/online_retail.xlsx
  local_data_file : artifacts/data_ingestion/online_retail.xlsx

pre_processing:
  data_path : artifacts/data_ingestion/online_retail.xlsx
  data_report : artifacts/data_report
  cleaned_data_save_path : artifacts/cleaned_data

feature_engg:
  data_path : artifacts/cleaned_data/pre_processed.csv 
  output_path : artifacts/feature_engg

EDA : 
  data_path : artifacts/feature_engg/rmf.csv
  report : artifacts/EDA

outlier:
  data_path : artifacts/feature_engg/rmf.csv
  output_path: artifacts/outlier
  report : artifacts/outlier/report
  
cluster :
  data_path : artifacts/outlier/rmf_final.csv
  cluster : artifacts/cluster
  report : artifacts/cluster/report 

model:
  data_path : artifacts/cluster/rmf_scaled.csv
  original_data : artifacts/outlier/rmf_final.csv
  kl_path : artifacts/cluster/kneelocator.pkl
  models : artifacts/models
  report : artifacts/models/report

prediction :
  model_path : artifacts/models/km_model.pkl
  scaler_path : artifacts/cluster/scaler.pkl

